// <auto-generated />
using System;
using CoinPay.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoinPay.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoinPay.Api.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ReceiverName")
                        .HasColumnType("text");

                    b.Property<string>("SenderName")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TransactionId")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 100.50m,
                            CompletedAt = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 10, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Payment for services",
                            ReceiverName = "Jane Smith",
                            SenderName = "John Doe",
                            Status = "Completed",
                            TransactionId = "TXN001",
                            Type = "Payment"
                        },
                        new
                        {
                            Id = 2,
                            Amount = 250.00m,
                            CompletedAt = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedAt = new DateTime(2025, 10, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Money transfer",
                            ReceiverName = "Bob Wilson",
                            SenderName = "Alice Johnson",
                            Status = "Completed",
                            TransactionId = "TXN002",
                            Type = "Transfer"
                        },
                        new
                        {
                            Id = 3,
                            Amount = 75.25m,
                            CreatedAt = new DateTime(2025, 10, 27, 0, 0, 0, 0, DateTimeKind.Utc),
                            Currency = "USD",
                            Description = "Pending payment",
                            ReceiverName = "David Lee",
                            SenderName = "Charlie Brown",
                            Status = "Pending",
                            TransactionId = "TXN003",
                            Type = "Payment"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
