# .github/workflows/docker-deploy.yml
# Place this file in: .github/workflows/docker-deploy.yml

name: Docker Compose CI/CD Pipeline

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - development
          - staging
          - production

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  pre-deployment-validation:
    name: Pre-Deployment Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check Docker and Docker Compose versions
        run: |
          docker --version
          docker-compose --version
          echo "✅ Docker tools verified"

      - name: Validate docker-compose.yml
        run: |
          cd deployment
          docker-compose config
          echo "✅ Docker Compose configuration valid"

      - name: Verify required files exist
        run: |
          test -f deployment/docker-compose.yml || exit 1
          test -f deployment/backup-restore.sh || exit 1
          test -f deployment/regression-test.sh || exit 1
          test -f deployment/DOCKER-COMPOSE-DEPLOYMENT.md || exit 1
          echo "✅ All required files present"

      - name: Check disk space
        run: |
          df -h
          FREE_GB=$(df -BG . | tail -1 | awk '{print $4}' | sed 's/G//')
          if [ ${FREE_GB} -lt 10 ]; then
            echo "❌ Insufficient disk space: ${FREE_GB}GB (minimum 10GB required)"
            exit 1
          fi
          echo "✅ Disk space OK: ${FREE_GB}GB available"

      - name: Lint Dockerfiles
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: CoinPay.Api/Dockerfile
          failure-threshold: error

  backup-current-state:
    name: Backup Current Production State
    runs-on: ubuntu-latest
    needs: pre-deployment-validation
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Docker Compose
        run: docker-compose version

      - name: Pull and start existing containers
        run: |
          cd deployment
          docker-compose pull || echo "No existing images to pull"
          docker-compose up -d || echo "No existing containers to start"
          sleep 15

      - name: Create comprehensive backup
        run: |
          cd deployment
          chmod +x backup-restore.sh
          ./backup-restore.sh backup || echo "Backup completed with warnings"

      - name: Upload backup artifact
        uses: actions/upload-artifact@v3
        with:
          name: pre-deployment-backup-${{ github.sha }}
          path: deployment/backups/
          retention-days: 30

      - name: Save backup manifest
        run: |
          cd deployment
          LATEST_BACKUP=$(ls -t backups/ | head -1)
          if [ -f "backups/${LATEST_BACKUP}/manifest.txt" ]; then
            cat "backups/${LATEST_BACKUP}/manifest.txt"
          fi

  build-api:
    name: Build API Container
    runs-on: ubuntu-latest
    needs: pre-deployment-validation
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-api-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-api-

      - name: Build API image
        run: |
          cd deployment
          docker-compose build --no-cache api

      - name: Test API container
        run: |
          cd deployment
          docker-compose up -d postgres vault
          sleep 15
          docker-compose up -d api
          sleep 20
          docker logs coinpay-api --tail 50

      - name: Verify API health
        run: |
          timeout 60 bash -c 'until curl -f http://localhost:7777/health; do sleep 5; done'
          echo "✅ API health check passed"

      - name: Stop containers
        if: always()
        run: |
          cd deployment
          docker-compose down

  build-gateway:
    name: Build Gateway Container
    runs-on: ubuntu-latest
    needs: pre-deployment-validation
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Gateway image
        run: |
          cd deployment
          docker-compose build --no-cache gateway

      - name: Verify Gateway image
        run: |
          docker images | grep coinpay-gateway
          echo "✅ Gateway image built successfully"

  build-web:
    name: Build Frontend Container
    runs-on: ubuntu-latest
    needs: pre-deployment-validation
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Web image
        run: |
          cd deployment
          docker-compose build --no-cache web

      - name: Test Web container
        run: |
          cd deployment
          docker-compose up -d web
          sleep 10
          curl -f http://localhost:3000 || exit 1
          echo "✅ Frontend loads successfully"

      - name: Check bundle size
        run: |
          cd deployment
          BUNDLE_SIZE=$(docker run --rm coinpay-web du -sh /usr/share/nginx/html | cut -f1)
          echo "Bundle size: ${BUNDLE_SIZE}"

      - name: Stop containers
        if: always()
        run: |
          cd deployment
          docker-compose down

  build-docs:
    name: Build Documentation Container
    runs-on: ubuntu-latest
    needs: pre-deployment-validation
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docs image
        run: |
          cd deployment
          docker-compose build --no-cache docfx

      - name: Verify Docs image
        run: |
          docker images | grep coinpay-docs
          echo "✅ Documentation image built successfully"

  integration-tests:
    name: Integration & Regression Tests
    runs-on: ubuntu-latest
    needs: [build-api, build-gateway, build-web, build-docs]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start all services
        run: |
          cd deployment
          docker-compose up -d
          sleep 30

      - name: Wait for services to be healthy
        run: |
          timeout 120 bash -c 'until docker exec coinpay-postgres-compose pg_isready -U postgres; do sleep 2; done'
          timeout 120 bash -c 'until curl -f http://localhost:7777/health; do sleep 5; done'
          echo "✅ All services healthy"

      - name: Initialize test data
        run: |
          docker exec -i coinpay-postgres-compose psql -U postgres -d coinpay <<EOF
          INSERT INTO "Users" ("Username", "CircleUserId", "CredentialId", "CreatedAt", "WalletAddress", "CircleWalletId")
          VALUES ('ci-test-user', 'ci-test-circle-id', 'ci-test-cred-id', NOW(), '0x1234567890123456789012345678901234567890', 'ci-test-wallet-id')
          ON CONFLICT DO NOTHING;
          EOF
          echo "✅ Test data initialized"

      - name: Run regression test suite
        run: |
          cd deployment
          chmod +x regression-test.sh
          ./regression-test.sh

      - name: Check data integrity
        run: |
          USER_COUNT=$(docker exec coinpay-postgres-compose psql -U postgres -d coinpay -t -c "SELECT COUNT(*) FROM \"Users\";")
          echo "User count: ${USER_COUNT}"
          if [ ${USER_COUNT} -eq 0 ]; then
            echo "❌ No users found - possible data loss"
            exit 1
          fi
          echo "✅ Data integrity verified"

      - name: Performance tests
        run: |
          echo "Running performance tests..."
          for i in {1..10}; do
            TIME=$(curl -s -o /dev/null -w "%{time_total}" http://localhost:7777/health)
            echo "Request $i: ${TIME}s"
          done

      - name: Generate test report
        if: always()
        run: |
          cd deployment
          cat > test-report.md <<EOF
          # CI/CD Test Report

          **Date**: $(date)
          **Commit**: ${{ github.sha }}
          **Branch**: ${{ github.ref_name }}

          ## Container Status
          \`\`\`
          $(docker-compose ps)
          \`\`\`

          ## Database Status
          \`\`\`
          $(docker exec coinpay-postgres-compose psql -U postgres -d coinpay -c "SELECT 'Users' as table, COUNT(*) FROM \"Users\" UNION ALL SELECT 'Transactions', COUNT(*) FROM \"Transactions\";")
          \`\`\`

          ## Service Logs
          ### API Logs (last 20 lines)
          \`\`\`
          $(docker logs coinpay-api --tail 20)
          \`\`\`
          EOF

      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-report-${{ github.sha }}
          path: deployment/test-report.md

      - name: Stop and clean up
        if: always()
        run: |
          cd deployment
          docker-compose down -v

  security-scan:
    name: Security Vulnerability Scan
    runs-on: ubuntu-latest
    needs: [build-api, build-gateway, build-web]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner - API
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'coinpay-api:latest'
          format: 'sarif'
          output: 'trivy-api-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-api-results.sarif'

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [backup-current-state, integration-tests, security-scan]
    if: github.ref == 'refs/heads/development'
    environment:
      name: staging
      url: https://staging.coinpay.example.com
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to staging server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.STAGING_SSH_KEY }}
          STAGING_HOST: ${{ secrets.STAGING_HOST }}
        run: |
          echo "Deploying to staging..."
          echo "✅ Staging deployment would execute here"
          # Actual deployment steps would go here

      - name: Post-deployment smoke tests
        run: |
          echo "Running smoke tests on staging..."
          # curl -f https://staging.coinpay.example.com/health

      - name: Notify deployment
        uses: 8398a7/action-slack@v3
        if: always()
        with:
          status: ${{ job.status }}
          text: '🚀 Staging deployment: ${{ job.status }}'
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [backup-current-state, integration-tests, security-scan]
    if: github.ref == 'refs/heads/main'
    environment:
      name: production
      url: https://coinpay.example.com
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download backup artifact
        uses: actions/download-artifact@v3
        with:
          name: pre-deployment-backup-${{ github.sha }}
          path: deployment/backups/

      - name: Deploy to production server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRODUCTION_SSH_KEY }}
          PRODUCTION_HOST: ${{ secrets.PRODUCTION_HOST }}
        run: |
          mkdir -p ~/.ssh
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          echo "Deploying to production..."

          # Copy deployment files
          scp -o StrictHostKeyChecking=no -r deployment/ ${PRODUCTION_HOST}:/opt/coinpay/

          # Execute deployment on server
          ssh -o StrictHostKeyChecking=no ${PRODUCTION_HOST} << 'ENDSSH'
            cd /opt/coinpay/deployment

            # Create backup before deployment
            ./backup-restore.sh backup

            # Graceful shutdown
            docker-compose down

            # Build new images
            docker-compose build --no-cache

            # Start with staged rollout
            docker-compose up -d postgres vault
            sleep 15

            docker-compose up -d api
            sleep 20

            docker-compose up -d gateway web docfx

            # Run regression tests
            ./regression-test.sh

            # Verify deployment
            docker-compose ps
          ENDSSH

      - name: Post-deployment validation
        run: |
          sleep 30
          # curl -f https://coinpay.example.com/health || exit 1
          echo "✅ Production deployment validated"

      - name: Notify deployment success
        uses: 8398a7/action-slack@v3
        with:
          status: 'success'
          text: '🎉 Production deployment successful! Commit: ${{ github.sha }}'
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}

  rollback-on-failure:
    name: Automatic Rollback
    runs-on: ubuntu-latest
    needs: [deploy-production]
    if: failure()
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download backup
        uses: actions/download-artifact@v3
        with:
          name: pre-deployment-backup-${{ github.sha }}
          path: deployment/backups/

      - name: Execute rollback
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRODUCTION_SSH_KEY }}
          PRODUCTION_HOST: ${{ secrets.PRODUCTION_HOST }}
        run: |
          mkdir -p ~/.ssh
          echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

          ssh -o StrictHostKeyChecking=no ${PRODUCTION_HOST} << 'ENDSSH'
            cd /opt/coinpay/deployment

            LATEST_BACKUP=$(ls -t backups/ | head -1)
            ./backup-restore.sh restore ${LATEST_BACKUP}

            # Verify rollback
            ./regression-test.sh
          ENDSSH

      - name: Notify rollback
        uses: 8398a7/action-slack@v3
        with:
          status: 'failure'
          text: '⚠️ Production deployment failed - Automatic rollback executed'
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
